import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Bibash Magar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col h-screen w-screen justify-center items-center'>
        <p className='font-sans font-black text-3xl'>BIBASH MAGAR</p>
      </main>
    </>
  )
}
